apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.pod.labels.app }}
spec:
  replicas: {{ .Values.pod.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.pod.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.pod.labels.app }}
    spec:
      containers:
        - name: "{{ .Values.pod.name }}"
          image: "{{.Values.pod.image}}:{{.Values.pod.tag}}"
          ports:
            - containerPort: {{ .Values.pod.port }}
