apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: {{ .Values.common.namespace }}
spec:
  selector:
    app: "{{ .Values.common.namespace }}-{{ .Values.nginx.name }}"
  ports:
    - port: 9000
